name: Build Torchlight2SharedStashManager

on:
  push:
    branches: [ '*' ]
    paths:
      - '**.cpp'
      - '**.h'
      - '**.pro'
      - '**.ui'
      - '**.qrc'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Qt5 5.15.2 MSVC2019_64
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: true

      - name: Create build directory
        run: mkdir build
      - name: Build with qmake
        run: |
          cd build
          qmake ../Torchlight2SharedStashManager.pro
          nmake

      - name: Deploy Qt dependencies
        run: |
          cd build\release
          windeployqt Torchlight2SharedStashManager.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Torchlight2-StashManager-Win64
          path: build/release/
